name: Security Scan

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Run Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar Dependências
        run: |
          sudo apt update
          sudo apt install -y bandit jq gitleaks
          
          # Instalar tfsec manualmente
          curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq -r '.assets[] | select(.name | test("linux_amd64")) | .browser_download_url' | xargs wget -O tfsec
          chmod +x tfsec && sudo mv tfsec /usr/local/bin/

          # Instalar trivy corretamente via script oficial
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh

      - name: Analisar Código Python
        run: bash security-scripts/scan_python_security.sh summary

      - name: Verificar Segredos Expostos
        run: bash security-scripts/scan_secrets.sh summary

      - name: Analisar Segurança no Terraform
        run: bash security-scripts/scan_tfsec.sh summary

      - name: Analisar Segurança no Docker
        run: bash security-scripts/scan_docker_security.sh summary meu-projeto
